export const PROFILE_HANDLECHANGE = 'profile::handlechange'
export const ADD_NEW_CHAT = 'chats::addNewChat'
export const ON_DELETE_CHAT = 'chats::onDeleteChat'
export const ON_ADD_MESSAGE ='messages::onAddMessage'
export const ON_DELETE_CHAT_MESSAGES = 'messages::onDeleteChatMessages'
export const FETCH_NEWS = 'news::fetchNews'
export const SHOW_LOADER = 'app::ShowLoader'
export const HIDE_LOADER = 'app::HideLoader'